Setup:
    n_tau           :   50 # N taus/batch
    n_batches       :   107200 # N batches train
    n_batches_val   :   19000 # N batches val
    input_dir       :   "/vols/cms/lcr119/Images/13082022/TestABCD"
    val_split       :   0.15 # proportion of files to be used for validation
    n_epochs        :   5
    epoch           :   0 # starting epoch
    model_name      :   "DeepPi_v1"
    dropout         :   0.2
    activation      :   "PReLu"
    optimiser       :   "NAdam"
    learning_rate   :   0.001
    override_files  :   False
    train_override  :   "/vols/cms/lcr119/Images/13082022/ABCTrain.txt"
    val_override    :   "/vols/cms/lcr119/Images/13082022/ABCVal.txt"
