Setup:
    n_tau           :   50 # N taus/batch
    n_batches       :   178600 # N batches train
    n_batches_val   :   31600 # N batches val
    input_dir       :   "/vols/cms/lcr119/Images/v2Images/Training" 
    val_split       :   0.15 # proportion of files to be used for validation
    n_epochs        :   5
    epoch           :   0 # starting epoch
    # Model name Guide:
    # DeepPi_v1: Mainly for DM (allows kinematic regression simultaneously)
    # DeepPi_v2: Exclusively for kinematic regression
    model_name      :   "DeepPi_v1" 
    dropout         :   0.0
    activation      :   "PReLu" # Not actually coded in yet
    optimiser       :   "NAdam" # Not actually coded in yet
    learning_rate   :   0.0001 # Not actually coded in yet
    kinematic       :   False  # Toggle True if want kinematic prediction as well as DM
    HPS_features    :   False  # Toggle True if want to use HPS high level mass variables
    DM_importance   :   1 # importance of gradients of DM
    kin_importance  :   1 # importance of gradients of kinematic loss