Setup:
    n_tau           :   50 # N taus/batch
    n_batches       :   1000 # N batches train
    n_batches_val   :   100 # N batches val
    input_dir       :   "/vols/cms/lcr119/Images/09082022/"
    val_split       :   0.2 # proportion of files to be used for validation
    n_epochs        :   20
    epoch           :   0 # starting epoch
    model_name      :   "DeepPi_v1"
